### ISSUE TITLE
Rebass in CodeSandbox doesn't work

### ISSUE THREAD

**Issue by joltmode** [rebassjs/rebass#459]
Don't know if it's CodeSandbox issue or Rebass issue or clean tag issue...  But happens only when making sandboxes with Rebass, styled-components/styled-system is okay.

Happens with linked example of README also: https://codesandbox.io/s/github/jxnblk/rebass/tree/master/examples/sandbox

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at evaluate (https://vv2kwkzyy.codesandbox.io/node_modules/clean-tag/dist.js:32:27)
    at oe (https://codesandbox.io/static/js/sandbox.886397df.js:1:293197)
    at e.value (https://codesandbox.io/static/js/sandbox.886397df.js:1:305118)
    at e.value (https://codesandbox.io/static/js/sandbox.886397df.js:1:276566)
    at d (https://codesandbox.io/static/js/sandbox.886397df.js:1:304912)
    at evaluate (https://vv2kwkzyy.codesandbox.io/node_modules/system-components/dist/System.js:17:17)
    at oe (https://codesandbox.io/static/js/sandbox.886397df.js:1:293197)
    at e.value (https://codesandbox.io/static/js/sandbox.886397df.js:1:305118)
    at e.value (https://codesandbox.io/static/js/sandbox.886397df.js:1:276566)
    at d (https://codesandbox.io/static/js/sandbox.886397df.js:1:304912)
    at evaluate (https://vv2kwkzyy.codesandbox.io/node_modules/system-components/dist/index.js:8:15)
    at oe (https://codesandbox.io/static/js/sandbox.886397df.js:1:293197)
    at e.value (https://codesandbox.io/static/js/sandbox.886397df.js:1:305118)
    at e.value (https://codesandbox.io/static/js/sandbox.886397df.js:1:276566)
    at d (https://codesandbox.io/static/js/sandbox.886397df.js:1:304912)
    at evaluate (https://vv2kwkzyy.codesandbox.io/node_modules/grid-styled/dist/Box.js:7:25)
    at oe (https://codesandbox.io/static/js/sandbox.886397df.js:1:293197)
    at e.value (https://codesandbox.io/static/js/sandbox.886397df.js:1:305118)
    at e.value (https://codesandbox.io/static/js/sandbox.886397df.js:1:276566)
    at d (https://codesandbox.io/static/js/sandbox.886397df.js:1:304912)
    at evaluate (https://vv2kwkzyy.codesandbox.io/node_modules/grid-styled/dist/index.js:7:12)
    at oe (https://codesandbox.io/static/js/sandbox.886397df.js:1:293197)
    at e.value (https://codesandbox.io/static/js/sandbox.886397df.js:1:305118)
    at e.value (https://codesandbox.io/static/js/sandbox.886397df.js:1:276566)
    at d (https://codesandbox.io/static/js/sandbox.886397df.js:1:304912)
    at evaluate (https://vv2kwkzyy.codesandbox.io/node_modules/rebass/dist/index.js:7:19)
    at oe (https://codesandbox.io/static/js/sandbox.886397df.js:1:293197)
    at e.value (https://codesandbox.io/static/js/sandbox.886397df.js:1:305118)
    at e.value (https://codesandbox.io/static/js/sandbox.886397df.js:1:276566)
    at d (https://codesandbox.io/static/js/sandbox.886397df.js:1:304912)
    at evaluate (https://vv2kwkzyy.codesandbox.io/src/App.js:14:15)
    at oe (https://codesandbox.io/static/js/sandbox.886397df.js:1:293197)
    at e.value (https://codesandbox.io/static/js/sandbox.886397df.js:1:305118)
    at e.value (https://codesandbox.io/static/js/sandbox.886397df.js:1:276566)
    at d (https://codesandbox.io/static/js/sandbox.886397df.js:1:304912)
    at evaluate (https://vv2kwkzyy.codesandbox.io/src/index.js:11:12)
    at oe (https://codesandbox.io/static/js/sandbox.886397df.js:1:293197)
    at e.value (https://codesandbox.io/static/js/sandbox.886397df.js:1:305118)
    at e.value (https://codesandbox.io/static/js/sandbox.886397df.js:1:276566)
    at e.value (https://codesandbox.io/static/js/sandbox.886397df.js:1:276339)
    at https://codesandbox.io/static/js/sandbox.886397df.js:1:95459
    at g (https://codesandbox.io/static/js/common-sandbox.edbc04b9.chunk.js:1:181333)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.edbc04b9.chunk.js:1:181121)
    at Generator.e.(anonymous function) [as next] (https://codesandbox.io/static/js/common-sandbox.edbc04b9.chunk.js:1:181512)
    at n (https://codesandbox.io/static/js/common-sandbox.edbc04b9.chunk.js:1:194432)
    at https://codesandbox.io/static/js/common-sandbox.edbc04b9.chunk.js:1:194528
```

**Comment by jxnblk** [comment]
I believe this is related to incorrect versions of being installed – the example template will need to be updated and tested

**Comment by testacode** [comment]
Any update on this? having the same issue, followed page instructions and when I try to import anything from rebass I get the following
![image](https://user-images.githubusercontent.com/1852080/44894623-170d0a00-acc7-11e8-84db-24c93639bc70.png)

Dependencies installed
![image](https://user-images.githubusercontent.com/1852080/44894637-2724e980-acc7-11e8-82ac-8b0f07ac9140.png)

Hope you can fix this. Thanks. The library is awesome.

**Comment by jxnblk** [comment]
Latest version *should* be working. Try the link in the README and let me know if you run into any more issues
